# netlify.toml
[build]
  # if you’re serving from the project root:
  publish = "."
  # or if your site is in `/public`, uncomment next line and remove the previous:
  # publish = "public"
  functions = "netlify/functions"

[functions]
  # ensure multipart/form-data bodies arrive as base64
  binary_media_types = ["multipart/form-data"]
