# netlify.toml
[build]
  
  publish = "."
  
  functions = "netlify/functions"

  [functions]
[functions."openai-proxy"]
  timeout = 25

    [functions.binary_media_types]
    external_node_modules = [
      "module-one",
      "module-two"
    ]
