# netlify.toml
[build]
  
  publish = "."
  
  functions = "netlify/functions"

  [functions]

  child_process_timeout = 25000

    [functions.binary_media_types]
    external_node_modules = [
      "module-one",
      "module-two"
    ]
